#!/bin/sh -xe
#
# Copyright (c) 2014 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Deploys the web interface to the label printer in Cambridge
# (http://labels.cam.xci-test.com/) used by the labeller netboot environment.
#
# On Debian, requires:
#
# apt-get install apache2 libbarcode-code128-perl libgd-barcode-perl \
#                 libgd-gd2-perl libgd-text-perl netpbm
#
# Also requires the host to have a network interface bound to
# labels.cam.xci-test.com.

# Give apache access to the printer

usermod -aG lp www-data

# Update apache configuration

LABELS_DIR=$(cd $(dirname $0) && /bin/pwd)

sed "s%@LABELS_DIR@%$LABELS_DIR%" apache/labels \
    > /etc/apache2/sites-available/labels

a2ensite labels

service apache2 restart

echo "Done!"
